package cli

// ClientConfigTemplate is the JSON template generated by generate-config --mode client.
const ClientConfigTemplate = `{
  "mode": "client",
  "client": {
    "tun": {
      "name": "",
      "address": "198.18.0.1/16",
      "mtu": 9000,
      "auto_route": true,
      "dns_hijack": true
    },
    "routing": {
      "default_action": "direct",
      "game_profiles": [
        {
          "id": "cs2",
          "displayName": "Counter-Strike 2",
          "enabled": true,
          "manual": true,
          "priority": 100,
          "match": {
            "processNames": ["cs2.exe"],
            "paths": [],
            "pathPrefixes": [],
            "sha256": [],
            "steamAppIds": [730]
          },
          "udpPolicy": "tgp",
          "tcpPolicy": "auto"
        }
      ],
      "launchers": {
        "steam": {
          "enabled": true,
          "trackChildProcesses": true,
          "accelerateGameUdp": true,
          "accelerateSteamDownloads": false
        }
      },
      "rules": [
        {
          "cidr": "192.168.0.0/16",
          "action": "direct",
          "priority": 50
        },
        {
          "geoip": "CN",
          "action": "direct",
          "priority": 10
        }
      ]
    },
    "proxy": {
      "server_addr": "your-game-relay.example.com:443",
      "tgp_server_addr": "your-game-relay.example.com:443"
    }
  },
  "tgp": {
    "fec": {
      "data_shards": 4,
      "parity_shards": 2,
      "group_timeout": "20ms",
      "dynamic": true,
      "adapt_window": 32
    },
    "pacing": {
      "initial_rate_pps": 128,
      "max_rate_pps": 1000
    },
    "connection_migration": true,
    "multipath": false,
    "handshake_timeout": "5s",
    "session_idle_timeout": "60s"
  },
  "ipc": {
    "websocket_addr": "127.0.0.1:55123",
    "grpc_addr": "127.0.0.1:50051",
    "telemetry_interval_ms": 500
  },
  "observability": {
    "log_level": "info",
    "log_file": "",
    "metrics_addr": ""
  }
}
`

// ServerConfigTemplate is the JSON template generated by generate-config --mode server.
const ServerConfigTemplate = `{
  "mode": "server",
  "server": {
    "listen": ":443",
    "relay": {
      "dial_timeout": "5s",
      "idle_timeout": "60s"
    }
  },
  "tgp": {
    "fec": {
      "data_shards": 4,
      "parity_shards": 2,
      "group_timeout": "20ms",
      "dynamic": true,
      "adapt_window": 32
    },
    "pacing": {
      "initial_rate_pps": 128,
      "max_rate_pps": 1000
    },
    "connection_migration": true,
    "multipath": true,
    "handshake_timeout": "5s",
    "session_idle_timeout": "300s"
  },
  "observability": {
    "log_level": "info",
    "log_file": "/var/log/tachyon/tachyon-core.log",
    "metrics_addr": "127.0.0.1:19090"
  }
}
`
